version: 2.1

jobs:
  build-push:
    docker:
      - image: cimg/base:2023.01
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          # Caching is expensive on CircleCI, and for a build this size, it's cheaper to avoid caching
          docker_layer_caching: false
      - run:
          name: Setup buildx and qemu
          command: |
            sudo apt update
            sudo apt install -y qemu-user-static binfmt-support
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker buildx create --name arm-builder
            docker buildx use arm-builder
            docker buildx inspect --bootstrap
      - run: docker login -u "$DOCKERHUB_USER_NAME" -p "$DOCKERHUB_ACCESS_TOKEN"
      - run: |
          docker buildx build --push --platform linux/arm64,linux/amd64 --tag ${DOCKERHUB_CONTAINER_NAMESPACE}/ln-backups:${CIRCLE_TAG:-$CIRCLE_BRANCH} .

workflows:
  docker-deployment:
    jobs:
      - build-push:
          context:
            - Docker builds
