version: 2.1

jobs:
  build-push:
    machine:
      image: "ubuntu-2204:2022.10.2"
    steps:
      - checkout
      - run:
          name: Setup buildx and qemu
          command: |
            sudo apt update
            sudo apt install -y qemu-user-static binfmt-support
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create arm-builder --docker "host=unix:///var/run/docker.sock"
            docker buildx create --name arm-builder arm-builder
            docker buildx use arm-builder
            docker buildx inspect --bootstrap
      - run: docker login -u "$DOCKERHUB_USER_NAME" -p "$DOCKERHUB_ACCESS_TOKEN"
      - run: |
          docker buildx build --push --platform linux/arm64,linux/amd64 --tag ${DOCKERHUB_CONTAINER_NAMESPACE}/ln-backups:${CIRCLE_TAG:-$CIRCLE_BRANCH} .

workflows:
  docker-deployment:
    jobs:
      - build-push:
          context:
            - Docker builds
